
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
class Solution {
public:
    char findTheDifference(string s, string t) {
     int n=s.length();
     char a=0;
       // if(s=="") return t[0];
        
        for(auto i:s)
        {
           a^=i; 
        }
        for(auto i:t)
        {
           a^=i; 
        }
        return a;
    }
};

class Solution {
public:
    char findTheDifference(string s, string t) {
     int n=s.length();
    char c1=0,c2=0;
       unordered_map<char,int> a;
        
        for(auto i:s)
        {
           c1+=i;
        }
        for(auto i:t)
        {
            
          c2+=i;
           
        }
        return c2-c1;
    }
};
